//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhutLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public int IDCustomers { get; set; }
        public string NameCustomers { get; set; }
        public string ChucvuCustomers { get; set; }
        public string CongTyCustomers { get; set; }
        public string CodeCustomers { get; set; }
        public string EmailCustomers { get; set; }
        public string PhoneCustomers { get; set; }
        public string FaxCustomers { get; set; }
        public string DiachiCustomers { get; set; }
        public string MasothueCustomers { get; set; }
        public Nullable<int> StatusCustomers { get; set; }
        public Nullable<System.DateTime> CreateDateCustomers { get; set; }
        public string CreateUserCustomers { get; set; }
        public Nullable<System.DateTime> ModifyDateCustomers { get; set; }
        public string ModifyUserCustomers { get; set; }
    }
    public class Totalcolumn
    {
        public string Namecustomers { get; set; }
        public string CodeDonhang { get; set; }
        public int ID_Donhang { get; set; }

        public int ID_Products { get; set; }
        public string NameProducts { get; set; }
        public Nullable<int> SolopProducts { get; set; }
        public string LoaigiayProducts { get; set; }
        public string OffsetFlexoProducts { get; set; }
        public string DanKimProducts { get; set; }
        public Nullable<int> SoluongProducts { get; set; }
        public string GiaProducts { get; set; }
        public Nullable<System.DateTime> CreatedDateProducts { get; set; }
        public Nullable<System.DateTime> ModifyDateProducts { get; set; }
        public string CreateUserProducts { get; set; }
        public string ModifyUserProducts { get; set; }
        public Nullable<int> StatusProducts { get; set; }
        public string CodeProducts { get; set; }
        public string QuyCachProducts { get; set; }
    }

}
